[versions]
euhedral-execution = "0.0.7"
junit = "5.11.4"
junit-platform = "1.11.4"
slf4j = "2.0.16"

[libraries]
euhedral-core = { module = "io.euhedral-execution:euhedral-core", version.ref = "euhedral-execution" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit-platform" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }

[plugins]
spotless = { id = "com.diffplug.spotless", version = "8.8.0" }